/* Generated By:JavaCC: Do not edit this line. AnsiCJTreeTreeConstants.java Version 5.0 */
package ansicjtree;

public interface AnsiCJTreeTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTADDITIVEEXPRESSION = 2;
  public int JJTMULTIPLICATIVEEXPRESSION = 3;
  public int JJTUNARYEXPRESSION = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTINTEGER = 6;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=5edc19f278585c993a0878061e9e0cb6 (do not edit this line) */
