/* Generated By:JavaCC: Do not edit this line. AnsiCTreeConstants.java Version 5.0 */
package ansicjtree;

public interface AnsiCTreeConstants
{
  public int JJTENTRADA = 0;
  public int JJTTOKEN = 1;


  public String[] jjtNodeName = {
    "entrada",
    "token",
  };
}
/* JavaCC - OriginalChecksum=f7028eff18cae6b08cb6c52d5449063e (do not edit this line) */
