/* Generated By:JavaCC: Do not edit this line. minilengcompilerConstants.java */
package minilengcompiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface minilengcompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tCOMENT = 5;
  /** RegularExpression Id. */
  int tPLUS = 6;
  /** RegularExpression Id. */
  int tMINUS = 7;
  /** RegularExpression Id. */
  int tMULTIPLY = 8;
  /** RegularExpression Id. */
  int tDIVIDE = 9;
  /** RegularExpression Id. */
  int tPROGRAMA = 10;
  /** RegularExpression Id. */
  int tAND = 11;
  /** RegularExpression Id. */
  int tOR = 12;
  /** RegularExpression Id. */
  int tNOT = 13;
  /** RegularExpression Id. */
  int tPRINCIPIO = 14;
  /** RegularExpression Id. */
  int tFIN = 15;
  /** RegularExpression Id. */
  int tSI = 16;
  /** RegularExpression Id. */
  int tENT = 17;
  /** RegularExpression Id. */
  int tSI_NO = 18;
  /** RegularExpression Id. */
  int tFSI = 19;
  /** RegularExpression Id. */
  int tMQ = 20;
  /** RegularExpression Id. */
  int tFMQ = 21;
  /** RegularExpression Id. */
  int tESCRIBIR = 22;
  /** RegularExpression Id. */
  int tLEER = 23;
  /** RegularExpression Id. */
  int tMOD = 24;
  /** RegularExpression Id. */
  int tDIV = 25;
  /** RegularExpression Id. */
  int tENTERO = 26;
  /** RegularExpression Id. */
  int tBOOLEANO = 27;
  /** RegularExpression Id. */
  int tCARACTER = 28;
  /** RegularExpression Id. */
  int tTRUE = 29;
  /** RegularExpression Id. */
  int tFALSE = 30;
  /** RegularExpression Id. */
  int tENTACAR = 31;
  /** RegularExpression Id. */
  int tCARAENT = 32;
  /** RegularExpression Id. */
  int tACCION = 33;
  /** RegularExpression Id. */
  int tVAL = 34;
  /** RegularExpression Id. */
  int tREF = 35;
  /** RegularExpression Id. */
  int tMAYOR = 36;
  /** RegularExpression Id. */
  int tMENOR = 37;
  /** RegularExpression Id. */
  int tIGUAL = 38;
  /** RegularExpression Id. */
  int tMAI = 39;
  /** RegularExpression Id. */
  int tMEI = 40;
  /** RegularExpression Id. */
  int tNI = 41;
  /** RegularExpression Id. */
  int tOPAS = 42;
  /** RegularExpression Id. */
  int tIDENTIFICADOR = 43;
  /** RegularExpression Id. */
  int DIGITO = 44;
  /** RegularExpression Id. */
  int LETRA = 45;
  /** RegularExpression Id. */
  int tCONST = 46;
  /** RegularExpression Id. */
  int tCAROCAD = 47;
  /** RegularExpression Id. */
  int tCOMA = 48;
  /** RegularExpression Id. */
  int tPUNTOYCOMA = 49;
  /** RegularExpression Id. */
  int tAPAR = 50;
  /** RegularExpression Id. */
  int tCPAR = 51;
  /** RegularExpression Id. */
  int tACOR = 52;
  /** RegularExpression Id. */
  int tCCOR = 53;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<tCOMENT>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"programa\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"principio\"",
    "\"fin\"",
    "\"si\"",
    "\"ent\"",
    "\"si_no\"",
    "\"fsi\"",
    "\"mq\"",
    "\"fmq\"",
    "\"escribir\"",
    "\"leer\"",
    "\"mod\"",
    "\"div\"",
    "\"entero\"",
    "\"booleano\"",
    "\"caracter\"",
    "\"true\"",
    "\"false\"",
    "\"entacar\"",
    "\"caraent\"",
    "\"accion\"",
    "\"val\"",
    "\"ref\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\":=\"",
    "<tIDENTIFICADOR>",
    "<DIGITO>",
    "<LETRA>",
    "<tCONST>",
    "<tCAROCAD>",
    "\",\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
  };

}
