/* Generated By:JavaCC: Do not edit this line. ExprMinConstants.java */
package test2;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExprMinConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int variable = 5;
  /** RegularExpression Id. */
  int constante = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "<variable>",
    "<constante>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
