/* Generated By:JavaCC: Do not edit this line. ExprMinConstants.java */
package test3;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExprMinConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int variable = 7;
  /** RegularExpression Id. */
  int constante = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "<token of kind 5>",
    "\"\\n\"",
    "<variable>",
    "<constante>",
  };

}
